### ISSUE TITLE
Files opened without closing

### ISSUE THREAD

**Issue by Lai-YT** [ntut-xuan/NuOJ-Sandbox#24]
# What's the problem?

Many places open a file and read the content directly as a one-liner.
The problem is that we lose the handle of the file handler and never close the file.

https://github.com/ntut-xuan/NuOJ-Sandbox/blob/e684fd83b64b7e374a8c983b64fef1463678e52e/backend/route/route.py#L38
https://github.com/ntut-xuan/NuOJ-Sandbox/blob/e684fd83b64b7e374a8c983b64fef1463678e52e/backend/tests/test.py#L31-L33

Just to name a few.

Not closing an open file is always a bad practice. See [Real Python: Why Is It Important to Close Files in Python?](https://realpython.com/why-close-file-python/) for some of the reasons.

# Any suggestion?

I suggest that we use [`Path.read_text()`](https://docs.python.org/3/library/pathlib.html) as the alternative. It's also a one-liner but closes the file for us.

```python
from pathlib import Path

content = Path('path/to/the/file').read_text()
```

I would like to know if you're aware of the above problem but intentionally left it still or if this isn't a problem.
Thanks.

**Comment by ntut-xuan** [comment]
Hi, @Lai-YT.

Thanks for finding the problem which occurs in the production code, we will solve it ASAP :)
